---
title: "Regession_EDA"
author: "Martin J Page"
date: "08/09/2020"
output: 
    html_document:
        keep_md: TRUE
---

Load libraries   
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(readr)
library(lubridate)
library(gridExtra)
```

Load Data   
```{r, results='hide'}
train <- read.csv("Train.csv")
test <- read.csv("Test.csv")

#format date
train$join_date <- as_date(train$join_date, format = "%d/%m/%Y")
test$join_date <- as_date(test$join_date, format = "%d/%m/%Y")
```

Format data   
```{r, results='hide'}
#format categorical variables as factors
#for (i in 9:29){
#    train[,i] <-  factor(as.character(train[,i]), levels = c("0", "1"), labels = c("No", "Yes"))
#}

train$sex <- factor(train$sex)
train$marital_status <- factor(train$marital_status)
train$branch_code <- factor(train$branch_code)
train$occupation_code <- factor(train$occupation_code)
train$occupation_category_code <- factor(train$occupation_category_code)

test$sex <- factor(test$sex)
test$marital_status <- factor(test$marital_status)
test$branch_code <- factor(test$branch_code)
test$occupation_code <- factor(test$occupation_code)
test$occupation_category_code <- factor(test$occupation_category_code)

#examine NAs
colnames(train)[colSums(is.na(train)) > 0]
colnames(test)[colSums(is.na(test)) > 0]

train[is.na(train[,"join_date"]),]
test[is.na(test[,"join_date"]),]
```
```{r}
#remove rows with NAs for EDA
train <- train[complete.cases(train),]
test <- test[complete.cases(test),]
```

Add feature columns
```{r}
#Add time elapsed
train$period_client <- 2020 - year(train$join_date)
test$period_client <- 2020 - year(test$join_date)

train$age <- 2020 - train$birth_year
train$join_year <- year(train$join_date)
train$age_join <- train$join_year - train$birth_year

test$age <- 2020 - test$birth_year
test$join_year <- year(test$join_date)
test$age_join <- test$join_year - test$birth_year

#number of products
train$number_products = rowSums(train[,c(which(colnames(train) == "P5DA"): which(colnames(train) == "ECY3"))])
```


Summary Statistics   
```{r, warning=FALSE}
#format categorical variables as factors
train_fct <- train
for (i in 9:29){
    train_fct[,i] <-  factor(as.character(train_fct[,i]), levels = c("0", "1"), labels = c("No", "Yes"))
}
summary(train_fct)
```
```{r}
#format categorical variables as factors
test_fct <- test
for (i in 9:29){
    test_fct[,i] <-  factor(as.character(test_fct[,i]), levels = c("0", "1"), labels = c("No", "Yes"))
}
summary(test_fct)
```

## Train vs Test
Join Date   
```{r}
year_train <- as.character(year(train$join_date))
month_train <- month(train$join_date, label = TRUE)
year_month <- paste(month_train, year_train)

p1 <- data.frame(year_month) %>% mutate(year_month = zoo::as.yearmon(year_month, "%b %Y")) %>%
    group_by(year_month) %>% summarise(count = length(year_month)) %>% ggplot(aes(x = year_month, y = count)) + geom_line() + ggtitle("Train")

year_test <- as.character(year(test$join_date))
month_test <- month(test$join_date, label = TRUE)
year_month_test <- paste(month_test, year_test)

p2 <- data.frame(year_month_test) %>% mutate(year_month = zoo::as.yearmon(year_month_test, "%b %Y")) %>%  group_by(year_month) %>% summarise(count = length(year_month)) %>% ggplot(aes(x = year_month, y = count)) + geom_line() + ggtitle("Test")
grid.arrange(p1, p2, nrow = 2)
```

Male vs Female   
```{r}
p3 <- train %>% ggplot(aes(sex, fill = sex)) + geom_bar() + ggtitle("Train")
p4 <- test %>% ggplot(aes(sex, fill = sex)) + geom_bar() + ggtitle("Test")
grid.arrange(p3, p4, ncol = 2) 
```
   
Marital Status   
```{r}
p5 <- train %>% ggplot(aes(marital_status, fill = marital_status)) + geom_bar() + ggtitle("Train")
p6 <- test %>% ggplot(aes(marital_status, fill = marital_status)) + geom_bar() + ggtitle("Test")
grid.arrange(p5, p6, ncol = 2) 
```
   
Birth Year   
```{r, fig.height= 7, fig.width= 10}
p7 <- train %>% ggplot(aes(birth_year)) + geom_bar() + ggtitle("Train")
p8 <- test %>% ggplot(aes(birth_year)) + geom_bar() + ggtitle("Test") + scale_x_continuous(limits = c(min(train$birth_year), max(train$birth_year)))
grid.arrange(p7, p8, nrow = 2)
```

Years elapsed since joined   
```{r, warning=FALSE}
p13 <- train %>% ggplot(aes(period_client)) + geom_bar() + ggtitle("Train")
p14 <- test %>% ggplot(aes(period_client)) + geom_bar() + ggtitle("Test")
grid.arrange(p13, p14, nrow = 2)
```
   
Branch Code   
```{r, fig.height= 6, fig.width= 8}
p9 <- train %>% ggplot(aes(branch_code, fill = branch_code)) + geom_bar() + ggtitle("Train") + theme(axis.text.x = element_text(angle = 90))
p10 <- test %>% ggplot(aes(branch_code, fill = branch_code)) + geom_bar() + ggtitle("Test") + theme(axis.text.x = element_text(angle = 90))
grid.arrange(p9, p10, ncol = 2)    
```
   
Occupation Code Category   
```{r, fig.height= 5, fig.width= 10}
p11 <- train %>% ggplot(aes(occupation_category_code, fill = occupation_category_code)) + geom_bar() + ggtitle("Train")
p12 <- test %>% ggplot(aes(occupation_category_code, fill = occupation_category_code)) + geom_bar() + ggtitle("Test")
grid.arrange(p11, p12, ncol = 2)
```
## Parameters vs Products
Correlation Matrix   
```{r}
corr_matrix <- cor(train[,c(5,9:ncol(train))])
corrplot::corrplot(corr_matrix, order = "FPC", method = "circle", type = "lower", tl.cex = 0.6, tl.col = "black")
```
    
Sex vs Products   
```{r, message=FALSE}
sex_summary <- train %>% group_by(sex) %>% select(P5DA:ECY3) %>% summarise_all(sum)
females <- sex_summary[1,-1] / sum(sex_summary[1,-1])
males <- sex_summary[2,-1] / sum(sex_summary[2,-1])
females <- females %>% mutate(sex = factor("F"))
males <- males %>% mutate(sex = factor("M"))

bind_rows(females, males) %>% pivot_longer(cols= -sex, names_to = "product" , values_to = "proportion") %>% ggplot(aes(x = product, y = proportion, fill = sex)) + geom_col(position = "dodge") + theme(axis.text.x = element_text(angle = 90))
```
    
Marital Status   
```{r, message=FALSE}
marital_products <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(marital_status, product) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "marital_status" ,names_from = "product", values_from = "total")

marital_products_mat <- apply(marital_products[,-1], MARGIN = 1, function(x) x / sum(x))
marital_products_mat <- data.frame(marital_products_mat)
colnames(marital_products_mat) <- pull(marital_products, marital_status)
marital_products_mat <- rownames_to_column(marital_products_mat, "product")
    
marital_products_mat %>% pivot_longer(cols= D:W, names_to = "marital_status" , values_to = "proportion") %>% ggplot(aes(x = marital_status, y = proportion, fill = product)) + geom_col()
```

```{r, message=FALSE}
marital_products <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(product, marital_status) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "product" ,names_from = "marital_status", values_from = "total")

marital_products_mat <- apply(marital_products[,-1], MARGIN = 1, function(x) x / sum(x))
marital_products_mat <- data.frame(marital_products_mat)
colnames(marital_products_mat) <- pull(marital_products, product)
marital_products_mat <- rownames_to_column(marital_products_mat, "marital_status")

marital_products_mat %>% pivot_longer(cols= AHXO:X8NN1, names_to = "product" , values_to = "proportion") %>% ggplot(aes(x = product, y = proportion, fill = marital_status)) + geom_col() + theme(axis.text.x = element_text(angle = 90))
```
   
Birth Year   
```{r}
birth_year <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(birth_year, product) %>% summarise(total = sum(purchase)) %>%  pivot_wider(id_cols = "birth_year" ,names_from = "product", values_from = "total")
birth_year <- column_to_rownames(birth_year, var = "birth_year")
birth_year <- apply(birth_year, MARGIN = 1, function(x) x / sum(x))
birth_year %>% knitr::kable()

```

```{r, fig.height= 6, fig.width= 9}
birth_year <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(product, birth_year) %>% summarise(total = sum(purchase)) %>%  pivot_wider(id_cols = "product" ,names_from = "birth_year", values_from = "total")
birth_year <- column_to_rownames(birth_year, var = "product")
birth_year <- apply(birth_year, MARGIN = 1, function(x) x / sum(x))

data.frame(birth_year) %>% mutate(birth_year = rownames(data.frame(birth_year)))%>% select(-GYSR) %>% pivot_longer(cols= AHXO:X8NN1, names_to = "product" , values_to = "proportion")  %>% ggplot(aes(x = birth_year, y = proportion)) + geom_col() + facet_wrap(~product) +  theme(axis.ticks.x = element_blank(), axis.text.x=element_blank())
```

   
Years elapsed since joined   
```{r}
year_products <- train %>% mutate(year_joined = year(join_date)) %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(year_joined, product) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "year_joined" ,names_from = "product", values_from = "total")

year_products_mat <- apply(year_products[,-1], MARGIN = 1, function(x) x / sum(x))
year_products_mat <- data.frame(year_products_mat)
colnames(year_products_mat) <- pull(year_products, year_joined)
year_products_mat <- rownames_to_column(year_products_mat, "product")
    
year_products_mat %>% pivot_longer(cols= "2010":"2020", names_to = "year_joined" , values_to = "proportion") %>% ggplot(aes(x = year_joined, y = proportion, fill = product)) + geom_col()
```

```{r}
year_products <- train %>% mutate(year_joined = year(join_date)) %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(product, year_joined) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "product" ,names_from = "year_joined", values_from = "total")

year_products_mat <- apply(year_products[,-1], MARGIN = 1, function(x) x / sum(x))
year_products_mat <- data.frame(year_products_mat)
colnames(year_products_mat) <- pull(year_products, product)
year_products_mat <- rownames_to_column(year_products_mat, "year_joined")
    
year_products_mat %>% pivot_longer(cols= AHXO:X8NN1, names_to = "product" , values_to = "proportion") %>% ggplot(aes(x = product, y = proportion, fill = year_joined)) + geom_col()  + theme(axis.text.x = element_text(angle = 90))
```
   
Branch Code   
```{r, message=FALSE}
branch_products <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(branch_code, product) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "branch_code" ,names_from = "product", values_from = "total")

branch_products_mat <- apply(branch_products[,-1], MARGIN = 1, function(x) x / sum(x))
branch_products_mat <- data.frame(branch_products_mat)
colnames(branch_products_mat) <- pull(branch_products, branch_code)
branch_products_mat <- rownames_to_column(branch_products_mat, "product")
    
branch_products_mat %>% pivot_longer(cols= "1X1H":"ZFER", names_to = "branch_code" , values_to = "proportion") %>% ggplot(aes(x = branch_code, y = proportion, fill = product)) + geom_col() + theme(axis.text.x = element_text(angle = 90))
```

```{r, message=FALSE}
branch_products <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(product, branch_code) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "product" ,names_from = "branch_code", values_from = "total")

branch_products_mat <- apply(branch_products[,-1], MARGIN = 1, function(x) x / sum(x))
branch_products_mat <- data.frame(branch_products_mat)
colnames(branch_products_mat) <- pull(branch_products, product)
branch_products_mat <- rownames_to_column(branch_products_mat, "branch_code")
    
branch_products_mat %>% pivot_longer(cols= "AHXO":"X8NN1", names_to = "product" , values_to = "proportion") %>% ggplot(aes(x = product, y = proportion, fill = branch_code)) + geom_col() + theme(axis.text.x = element_text(angle = 90))
```
   
Occupation Category   
```{r, message=FALSE}
occupation_products <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(occupation_category_code, product) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "occupation_category_code" ,names_from = "product", values_from = "total")

occupation_products_mat <- apply(occupation_products[,-1], MARGIN = 1, function(x) x / sum(x))
occupation_products_mat <- data.frame(occupation_products_mat)
colnames(occupation_products_mat) <- pull(occupation_products, occupation_category_code)
occupation_products_mat <- rownames_to_column(occupation_products_mat, "product")
    
occupation_products_mat %>% pivot_longer(cols= "56SI":"T4MS", names_to = "occupation_category_code" , values_to = "proportion") %>% ggplot(aes(x = occupation_category_code, y = proportion, fill = product)) + geom_col()
```

```{r, message=FALSE}
occupation_products <- train %>% pivot_longer(cols= P5DA:ECY3, names_to = "product" , values_to = "purchase") %>% group_by(product, occupation_category_code) %>% summarise(total = sum(purchase)) %>% pivot_wider(id_cols = "product" ,names_from = "occupation_category_code", values_from = "total")

occupation_products_mat <- apply(occupation_products[,-1], MARGIN = 1, function(x) x / sum(x))
occupation_products_mat <- data.frame(occupation_products_mat)
colnames(occupation_products_mat) <- pull(occupation_products, product)
occupation_products_mat <- rownames_to_column(occupation_products_mat, "occupation_category_code")
    
occupation_products_mat %>% pivot_longer(cols= "AHXO":"X8NN1", names_to = "product" , values_to = "proportion") %>% ggplot(aes(x = product, y = proportion, fill = occupation_category_code)) + geom_col() + theme(axis.text.x = element_text(angle = 90))
```


